CREATE DATABASE IF NOT EXISTS diaryapp;
USE diaryapp;
CREATE TABLE IF NOT EXISTS entries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL
);
GRANT ALL PRIVILEGES ON diaryapp.* TO 'root'@'localhost';
FLUSH PRIVILEGES;
